# Listener interne (backend, telegraf - reseau Docker)
listener 1883
allow_anonymous true

# Listener externe TLS pour clients distants (mini PC, Raspberry Pi)
listener 8883
allow_anonymous true
cafile /mosquitto/certs/ca.crt
certfile /mosquitto/certs/server.crt
keyfile /mosquitto/certs/server.key
require_certificate false
tls_version tlsv1.2

persistence true
persistence_location /mosquitto/data/
log_dest stdout
